In [3]:
word_ls = ['원숭이','바나나','사과','코끼리']

In [4]:
from collections import defaultdict
import numpy as np

In [5]:
word2id_dic = defaultdict(lambda:len(word2id_dic))
word2id_dic # {단어:인덱스} 딕셔너리 만든다

defaultdict(<function __main__.<lambda>()>, {})

In [6]:
for word in word_ls:
    word2id_dic[word] # 단어를 넣어준다
word2id_dic

defaultdict(<function __main__.<lambda>()>,
            {'원숭이': 0, '바나나': 1, '사과': 2, '코끼리': 3})

In [7]:
n_unique_words = len(word2id_dic)
n_unique_words #고유단어갯수:4개

4

In [8]:
# 원핫벡터를 만들기 위해 비어있는 벡터 생성
# np.zeroes((len(word_ls),len(word_ls)))로 해도 무방
one_hot_vectors = np.zeros((len(word_ls), n_unique_words))
one_hot_vectors

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# 단어고유 인덱스

for i, word in enumerate(word_ls): # 딕서녀리의 key,value 나열
    index = word2id_dic[word]
    one_hot_vectors[i,index] +=1 #단어 고유 인덱스에 1을 더한다
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
# sklearn을 활용하여 원핫인코딩
!pip install sklearn

In [11]:
import numpy as np
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [12]:
values = array(word_ls) # 배열 형태
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [13]:
# 라벨인코더

label_enc = LabelEncoder() # 선언
int_enc = label_enc.fit_transform(values) # 문자열에 숫자를 붙임
int_enc # 순서대로가 아닌건 컴퓨터가 랜덤으로 부여한거

array([2, 0, 1, 3], dtype=int64)

In [14]:
# 원핫인코더

onehot_enc = OneHotEncoder(sparse=False) # sparse: Will return sparse matrix if set True else will return an array.
int_enc = int_enc.reshape(len(int_enc), 1) # n:1 행렬로 변환
onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [15]:
# sklearn을 사용하면 3단계를 거쳐서 원핫인코딩을 실행할 수 있음

In [16]:
# BoW 직접구현 / sklearn / gensim
# BoW = Bag of Words

In [17]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
       '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [18]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls # 띄어쓰기로 토큰화

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [19]:
from collections import defaultdict
import numpy as np

In [20]:
word2id = defaultdict(lambda:len(word2id))
word2id # 딕서녀리로 만들어줌

defaultdict(<function __main__.<lambda>()>, {})

In [21]:
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id # unique한 토큰들을 인덱스화

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [22]:
n_unique_words_2 = len(word2id)
n_unique_words_2

9

In [25]:
bow_vec = []

for i,doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] += 1 # 해당 토큰의 위치 (column)
    bow_vec.append(bow.tolist())

bow_vec

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [27]:
!pip install pandas

In [31]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value, key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [32]:
vocab = []
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [33]:
for i in range(len(docs)):
    print('문서{} : {}'.format(i, docs[i]))
    ICD.display(pd.DataFrame([bow_vec[i]], columns = vocab))
    print('\n\n')

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1