## TDM 직접구현 

In [1]:
docs = ['동물원 코끼리', 
       '동물원 원숭이 바나나',
       '엄마 코끼리 아기 코끼리',
       '원숭이 바나나 코끼리 바나나']

In [2]:
doc_ls = []
for doc in docs : 
    doc_ls.append(doc.split())
doc_ls

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [3]:
from collections import defaultdict
import numpy as np
word2id_dic = defaultdict(lambda: len(word2id_dic))

In [4]:
for doc in doc_ls: 
    for token in doc: 
        word2id_dic[token]
word2id_dic
# doc_ls에 있는 단어 묶음들에서 doc(단어 하나씩을 matching시키자), 그리고
# unique한 토큰을 word2id_dic dictionary에 넣어주자

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

In [5]:
import numpy as np

TDM = np.zeros((len(word2id_dic), len(doc_ls)), dtype=int)
print(TDM)
for i, doc in enumerate(doc_ls):
    for token in doc: 
        TDM[word2id_dic[token], i] += 1
#행렬로 표기(Bow와의 차이점: Bow는 1차원 배열)

# for i, doc in enumerate(doc_ls):
#     tdm = np.zeros(len(word2id_dic), dtype = int)
#     for token in doc:
#         tdm[word2id_dic[token]] += 1
#     TDM.append(tdm.tolist())
#     TDM

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
import pandas as pd 

doc_names = ['문서' + str(i) for i in range(len(doc_ls))]
print('doc_names', doc_names)
sorted_vocab = sorted((value, key) for key, value in word2id_dic.items())
sorted_vocab #무엇을 구했는지 확인


doc_names ['문서0', '문서1', '문서2', '문서3']


[(0, '동물원'), (1, '코끼리'), (2, '원숭이'), (3, '바나나'), (4, '엄마'), (5, '아기')]

In [11]:
vocab = [v[1] for v in sorted_vocab] # for문을 간단화한 거임
df_TDM = pd.DataFrame(TDM, columns = doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
원숭이    0    1    0    1
바나나    0    1    0    2
엄마     0    0    1    0
아기     0    0    1    0

## sklearn

In [21]:
docs = ['동물원 코끼리', 
       '동물원 원숭이 바나나',
       '엄마 코끼리 아기 코끼리',
       '원숭이 바나나 코끼리 바나나']

In [22]:
from sklearn.feature_extraction.text import CountVectorizer
# 참고 sklearn은 DTM으로 만들어지게 설정되어 있음
count_vect = CountVectorizer()
TDM = count_vect.fit_transform(docs)
TDM.toarray()

array([[1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 2],
       [0, 2, 0, 0, 1, 1]], dtype=int64)

In [23]:
TDM.toarray().T  # TDM 보고싶으면 .T(transpose)로 설정하면 됨 

array([[1, 1, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 2, 1]], dtype=int64)

In [24]:
import pandas as pd 

doc_names = ['문서' + str(i) for i in range(len(doc_ls))]
vocab = count_vect.get_feature_names()
print(vocab)
df_TDM = pd.DataFrame(TDM.toarray().T, columns = doc_names)
df_TDM['단어'] = vocab 
df_TDM.set_index('단어')

['동물원', '바나나', '아기', '엄마', '원숭이', '코끼리']


문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
바나나    0    1    0    2
아기     0    0    1    0
엄마     0    0    1    0
원숭이    0    1    0    1
코끼리    1    0    2    1

## gensim 

In [25]:
docs = ['동물원 코끼리', 
       '동물원 원숭이 바나나',
       '엄마 코끼리 아기 코끼리',
       '원숭이 바나나 코끼리 바나나']

In [27]:
id2word = corpora.Dictionary(doc_ls)
TDM = [id2word.doc2bow(doc) for doc in doc_ls]
TDM

[[(0, 1), (1, 1)],
 [(0, 1), (2, 1), (3, 1)],
 [(1, 2), (4, 1), (5, 1)],
 [(1, 1), (2, 2), (3, 1)]]

In [28]:
import gensim 
from gensim import corpora 

print(id2word )


#TDM = [id2word.doc2bow(doc) for doc in doc_ls]은 아래 for문과 같은 식 

TDM =[]
for doc in doc_ls:
    TDM.append(id2word.doc2bow(doc))

doc_ls = [doc.split() for doc in docs] #공백으로 토큰화 
# doc_ls=[]
# for doc in docs : 
#     doc_ls.append(doc.split()) 위 doc_ls 식이 for문과 같은 기능함(더 짧은 version)

doc_ls

Dictionary(6 unique tokens: ['동물원', '코끼리', '바나나', '원숭이', '아기']...)


[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [35]:
from gensim.matutils import sparse2full  # sparse2full 0으로 채워주는 것 
import pandas as pd 
import numpy as np 
doc_names = ['문서' + str(i) for i in range(len(doc_ls))]
vocab = [id2word[i] for i in id2word.keys()]
DTM_matrix = [sparse2full(doc, len(vocab)).tolist() for doc in TDM]

df_TDM = pd.DataFrame(np.array(DTM_matrix, dtype = int).T, columns = doc_names)

df_TDM['단어'] = vocab 
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
바나나    0    1    0    2
원숭이    0    1    0    1
아기     0    0    1    0
엄마     0    0    1    0