# 원핫인코딩 직접구현
- 데이터 분석가는 직접구현을 하는 게 맞지만
- 마케팅에서 데이터 분석을 강점으로 가져가고 싶다면 라이브러리 사용해서 익숙하게

In [10]:
#인코딩 대상 단어를 담은 리스트
word_ls=['원숭이','바나나','사과','코끼리']

In [4]:
from collections import defaultdict
import numpy as np

In [8]:
# {단어:인덱스} 사전구축
word2id_dic = defaultdict(lambda:len(word2id_dic))

for word in word_ls:
    word2id_dic[word]

#고유단어 갯수 : 4개
n_unique_words = len(word2id_dic)

#원핫 벡터를 만들기 위해 비어있는 벡터 생성
one_hot_vectors = np.zeros((len(word_ls), n_unique_words))

In [9]:
# 단어 고유 인덱스
for i, word in enumerate(word_ls):
    index = word2id_dic[word]
    one_hot_vectors[i,index] += 1 # 단어 고유 인덱스에 1을 더해줌
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# 라이브러리 사용해서 구현

# sklearn을 활용한 one-hot encoding

In [13]:
#sklearn 을 이용한 one-hot encoding  3단계로 
from numpy import array
from numpy import argmax # 큰값부터 sorting 하는거
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [14]:
word_ls

['원숭이', '바나나', '사과', '코끼리']

In [17]:
#예제 데이터 배열
values = array(word_ls) # 리스트였던 word_ls 배열로 바꿔주기
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [18]:
# 문자열에 숫자를 붙임
label_enc = LabelEncoder() # labelencoder 쓸거라고 선언
int_enc = label_enc.fit_transform(values)
int_enc # 나온 숫자값들은 컴퓨터가 알아서 붙인거임..

array([2, 0, 1, 3], dtype=int64)

In [21]:
#binary ecndoe
onehot_enc=OneHotEncoder(sparse=False) #선언(False로 디폴트 인데, true로하면 행렬로나오고, False로하면 배열로나옴)
int_enc = int_enc.reshape(len(int_enc),1) # n:1 matrix로 변환
onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])