# 원핫인코딩 직접구현

In [5]:
word_ls=['원숭이','바나나','사과','코끼리']

In [7]:
from collections import defaultdict
import numpy as np

#{단어:안덱스} 사전구축
word2id_dic=defaultdict(lambda:len(word2id_dic))
word2id_dic


defaultdict(<function __main__.<lambda>()>, {})

In [8]:

for word in word_ls:
     word2id_dic[word]


In [9]:
#고유 단어 갯수:4개
n_unique_words=len(word2id_dic)

#원핫 벡터를 만들기 위해 비어있는 벡터 생성
one_hot_vectors=np.zeros((len(word_ls),n_unique_words))

#단어고유 인덱스
for i, word in enumerate(word_ls):
    index=word2id_dic[word]
    one_hot_vectors[i,index]+=1 
one_hot_vectors    

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# sklearn 이용

In [10]:
# sklearn 을 활용한 one-hot encoding

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#예제 데이터 배열
values=array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [11]:
#문자열에 숫자를 붙임

label_enc=LabelEncoder() #선언
int_enc=label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3], dtype=int64)

In [12]:
#binary encode

onehot_enc=OneHotEncoder(sparse=False) #선언
int_enc=int_enc.reshape(len(int_enc),1)
print(int_enc)
onehot_enc=onehot_enc.fit_transform(int_enc)
onehot_enc

[[2]
 [0]
 [1]
 [3]]


array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

# BOW 직접 구현

In [23]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
     '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [24]:
#띄어쓰기 토큰화

doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls    

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [25]:
from collections import defaultdict
word2id=defaultdict(lambda: len(word2id))
word2id

defaultdict(<function __main__.<lambda>()>, {})

In [26]:
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id        
    

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [27]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    for token in doc:
        bow[word2id[token]]+=1
    BoW_ls.append(bow.tolist())

In [28]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [29]:

from IPython.core import display as ICD

sorted_vocab = sorted((value, key) for key, value in word2id.items())

print(sorted_vocab)


[(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [30]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)    
    

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [31]:
import pandas as pd 

vocab = [v[1] for v in sorted_vocab]

for i in range(len(docs)) :

    print("문서{} : {}".format(i, docs[i]))

    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))

    print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

In [32]:
docs = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
        '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']
docs

['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해', '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [33]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls    

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [34]:
from collections import defaultdict
word2id=defaultdict(lambda: len(word2id))
word2id

defaultdict(<function __main__.<lambda>()>, {})

In [35]:
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id        

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [36]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    for token in doc:
        bow[word2id[token]]+=1
    BoW_ls.append(bow.tolist())
BoW_ls

[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [37]:
from IPython.core import display as ICD

sorted_vocab = sorted((value, key) for key, value in word2id.items())

print(sorted_vocab)


[(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]


In [38]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)    
    

vocab ['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']


In [39]:
import pandas as pd 

vocab = [v[1] for v in sorted_vocab]

for i in range(len(docs)) :

    print("문서{} : {}".format(i, docs[i]))

    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))

    print("\n\n")

문서0 : 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1 : 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1