# TDM 직접구현

In [1]:
docs=['동물원 코끼리',
     '동물원 원숭이 바나나',
     '엄마 코끼리 아기 코끼리',
     '원숭이 바나나 코끼리 바나나']

In [2]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls    

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [3]:
from collections import defaultdict



word2id = defaultdict(lambda : len(word2id))

[word2id[token] for doc in doc_ls for token in doc ]     

word2id  

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

In [4]:
import numpy as np
TDM=np.zeros((len(word2id),len(doc_ls)),dtype=int)
print(TDM)

for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token],i]+=1
        
TDM       

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[1, 1, 0, 0],
       [1, 0, 2, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [5]:
import pandas as pd

doc_names=['문서'+str(i)for i in range(len(doc_ls))]
sorted_vocab=sorted((value,key)for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]

df_TDM=pd.DataFrame(TDM,columns=doc_names)
df_TDM['단어']=vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
원숭이    0    1    0    1
바나나    0    1    0    2
엄마     0    0    1    0
아기     0    0    1    0

# gensim 이용한 TDM

In [6]:
docs=['동물원 코끼리',
     '동물원 원숭이 바나나',
     '엄마 코끼리 아기 코끼리',
     '원숭이 바나나 코끼리 바나나']

In [7]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls    

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [8]:
from collections import defaultdict



word2id = defaultdict(lambda : len(word2id))

[word2id[token] for doc in doc_ls for token in doc ]     

word2id  


defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

In [9]:
import gensim 
from gensim import corpora

doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split())
    
print(doc_ls)

id2word=corpora.Dictionary(doc_ls)

TDM=[id2word.doc2bow(doc) for doc in doc_ls]
TDM

[['동물원', '코끼리'], ['동물원', '원숭이', '바나나'], ['엄마', '코끼리', '아기', '코끼리'], ['원숭이', '바나나', '코끼리', '바나나']]


[[(0, 1), (1, 1)],
 [(0, 1), (2, 1), (3, 1)],
 [(1, 2), (4, 1), (5, 1)],
 [(1, 1), (2, 2), (3, 1)]]

In [10]:
from gensim.matutils import sparse2full
import pandas as pd
import numpy as np
doc_names=['문서'+str(i) for i in range(len(doc_ls))]
vocab=[id2word[i] for i in id2word.keys()]
DTM_matrix=[sparse2full(doc,len(vocab)).tolist() for doc in TDM]

df_TDM=pd.DataFrame(np.array(DTM_matrix,dtype=int).T,columns=doc_names)
df_TDM['단어']=vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
바나나    0    1    0    2
원숭이    0    1    0    1
아기     0    0    1    0
엄마     0    0    1    0