# BoW 직접구현

In [3]:
docs=['오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [4]:
#'띄어쓰기'를 기준으로 토큰화
doc_ls=[]

for doc in docs:
    doc_ls.append(doc.split(' '))
    
print(doc_ls)

#텅 빈 기본 딕셔너리
from collections import defaultdict
word2id = defaultdict(lambda :len(word2id))



[['오늘', '동물원에서', '코끼리,', '원숭이를', '보고', '코끼리,', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]


In [5]:
for doc in doc_ls:
    for token in doc:
        word2id[token]

word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리,': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [6]:
doc_ls

[['오늘', '동물원에서', '코끼리,', '원숭이를', '보고', '코끼리,', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [7]:
import numpy as np
BoW_ls =[]
for i, doc in enumerate(doc_ls):
    bow= np.zeros(len(word2id), dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] += 1 # 해당 토큰의 위치(column)
    BoW_ls.append(bow.tolist())
#1차원 배열
BoW_ls

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [8]:
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리,': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [9]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value,key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리,'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [10]:
vocab =[]
for v in sorted_vocab :
    vocab.append(v[1])
print('vocab', vocab)

vocab ['오늘', '동물원에서', '코끼리,', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [13]:
import pandas as pd
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
    print("\n\n")

문서0:오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리,  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1     2     1   1      1    1   1    0




문서1:오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리,  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1     0     0   0      1    0   1    1

In [14]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

# 단어의 순서를 고려하지 않은 BOW

In [15]:
docs2 = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
        '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [16]:
doc2_ls=[]

for doc in docs2:
    doc2_ls.append(doc.split(' '))

In [17]:
doc2_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [18]:
from collections import defaultdict
word2id2 = defaultdict(lambda :len(word2id2))

In [19]:
for doc in doc2_ls:
    for token in doc:
        word2id2[token]
word2id2
#for 문을 2번 돌려서, 1번째 for에서 단어 추출, 2번째 for에서 token

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [20]:
import numpy as np

BoW_ls2 =[]
for i , doc in enumerate(doc2_ls):
    bow = np.zeros(len(word2id2), dtype=int)
    print(bow)
    for token in doc:
        bow[word2id2[token]] +=1
    BoW_ls2.append(bow.tolist())
BoW_ls2

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [22]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value,key) for key, value in word2id2.items())


vocab =[]
for v in sorted_vocab :
    vocab.append(v[1])
print('vocab', vocab)

import pandas as pd
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW_ls2[i]], columns=vocab))
    print("\n\n")

vocab ['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']
문서0:오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1:오늘 동물원에서 원숭이에게 사과를 줬어


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1

# sklearn

In [28]:
docs=['오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어', '오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [29]:
# 토큰빈도계산 : CounterVetorizer
#이것만 호출
from sklearn.feature_extraction.text import CountVectorizer

#선언
count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs) #input = docs 리스트 통째로
BoW #우리가 인지하기 어려운 형태

<2x9 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [30]:
BoW.toarray()

array([[1, 1, 1, 0, 1, 1, 1, 1, 2],
       [2, 1, 1, 1, 2, 1, 2, 2, 2]], dtype=int64)

In [31]:
# 각각토큰 추출
vocab = count_vect.get_feature_names()
print(vocab)

['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [37]:
from IPython.core import display as ICD
import pandas as pd

for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab))
   
    df = pd.DataFrame([BoW.toarray()[i]], columns=vocab)
    print(df)
  

문서0:오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2

   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2
문서1:오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2

   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2


# gensim

In [39]:
! pip install gensim

  Created wheel for smart-open: filename=smart_open-2.1.1-py3-none-any.whl size=112418 sha256=2f5e63c0863c1cb4e386a27d2b1ca461380d49ce2712b4f3df38751ce0b24509
  Stored in directory: c:\users\lg\appdata\local\pip\cache\wheels\07\d8\70\da31eb9ec5ff49ac74f1a5944704029f0b6fd74fdf318ec300
Successfully built smart-open


In [40]:
from gensim import corpora

#문서를 토큰화
doc_ls = []
for doc in docs:
    doc_ls.append(doc.split()) 
print(doc_ls)
# 딕셔너리에 토큰화한 문서 입력 

id2word = corpora.Dictionary(doc_ls)
print('-----------')
print(id2word)

# BoW
BoW = []
for doc in doc_ls:
    BoW.append(id2word.doc2bow(doc))

BoW

[['오늘', '동물원에서', '코끼리,', '원숭이를', '보고', '코끼리,', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '코끼리,', '원숭이를', '보고', '코끼리,', '원숭이에게', '먹이를', '줬어', '오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]
-----------
Dictionary(9 unique tokens: ['동물원에서', '먹이를', '보고', '오늘', '원숭이를']...)


[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 2), (1, 1), (2, 1), (3, 2), (4, 1), (5, 2), (6, 2), (7, 2), (8, 1)]]

In [41]:
BoW[0]

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)]

In [44]:
# sparse2full을 사용해서 알기 어렵게 표기된 gensim값을 알기 쉽게 바꿈
#gensim은 컬럼값이 0인 부분 생략
# sparse2full을 통해서 비어있는 컬럼의 0값을 채워줌
# sparse하다 = 0이 있다 / 많다

from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd
vocab = [id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
    print("문서{}:{}".format(i,docs[i]))
    ICD.display(pd.DataFrame([sparse2full(BoW[i], len(vocab))], columns=vocab))

문서0:오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리,  사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0   2.0  0.0

문서1:오늘 동물원에서 코끼리, 원숭이를 보고 코끼리, 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리,  사과를
0    2.0  1.0  1.0  2.0   1.0    2.0  2.0   2.0  1.0