# **원핫인코딩 직접구현**

In [2]:
#인코딩 대상 단어를 담은 리스트
word_ls=['원숭이', '바나나', '사과', '코끼리']

In [20]:
from collections import defaultdict
import numpy as np

# (단어/인덱스) 사전구축
word2id_dic=defaultdict(lambda:len(word2id_dic))
word2id_dic

defaultdict(<function __main__.<lambda>()>, {})

In [21]:
for word in word_ls:
    word2id_dic[word]

word2id_dic[word]

3

In [12]:
#고유단어갯수 : 4개
n_unique_words=len(word2id_dic)

In [17]:
#원핫 벡터를 만들기 위해 비어있는 벡터 생성
one_hot_vectors=np.zeros((len(word_ls), n_unique_words))

In [19]:
#단어고유 인덱스
for i, word in enumerate(word_ls):
    index=word2id_dic[word]
    one_hot_vectors[i,index]+=1 #단어 고유 인덱스에 1을 더해줌

one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Sklearn

In [ ]:
#sklearn 패키지로 원핫인코딩 하기

#단어 리스트 -> 배열(array)형태로 변환
-------- #라벨 인코더
# 문자열에 숫자를 붙임

----- #라벨 인코더값을 원핫 인코더 전환
# 패키지 호출 및 사용 선언

#transform - array를 라벨 인코더에 넣어준다
#sklearn의 규칙: 피팅 후 트랜스폼[행렬 전환] 필수
--- 
#원핫인코더에 값을 넣어줄 것
#reshape [세로->가로 배열] 후 핏 ->트랜스폼



In [1]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [3]:
#예제 데이터 배열
values = array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [4]:
# 문자열에 숫자를 붙임

#LabelEncoder 선언
label_enc = LabelEncoder()
int_enc = label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3], dtype=int64)

In [6]:
#binary encode

#OneHotEncoder 선언
onehot_enc=OneHotEncoder(sparse=False)

# n:1 matrix로 변환
int_enc=int_enc.reshape(len(int_enc),1)

onehot_enc=onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])