# BOW 직접 구현

In [1]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
       '오늘 동물원에서 원숭이에게 사과를 줬어']

In [2]:
# 띄어쓰기 토큰화 
doc_ls = []
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [3]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id))
word2id

defaultdict(<function __main__.<lambda>()>, {})

In [4]:
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [5]:
import numpy as np
bow_vectors = np.zeros(len(word2id))
bow_vectors

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
for i in doc_ls:
    print(i)
    for word in i:
        print(word)
        index = word2id[word]
        bow_vectors[index] += 1

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어']
오늘
동물원에서
코끼리
원숭이를
보고
코끼리
원숭이에게
먹이를
줬어
['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']
오늘
동물원에서
원숭이에게
사과를
줬어


In [7]:
bow_vectors

array([2., 2., 2., 1., 1., 2., 1., 2., 1.])

- 다른 방법

In [10]:
import numpy as np
BoW_ls = []
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] += 1 # 해당 토큰의 위치(column)
        print(word2id[token])
    BoW_ls.append(bow.tolist())
# 1차원 배열
BoW_ls

[0 0 0 0 0 0 0 0 0]
0
1
2
3
4
2
5
6
7
[0 0 0 0 0 0 0 0 0]
0
1
5
8
7


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

- ICD 라이브러리를 활용하여 확인

In [12]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value, key) for key, value in word2id.items())
print('sorted_vocab',sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [13]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [14]:
for i in range(len(docs)):
    print("문서{} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
    print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

In [15]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

# 단어의 순서를 고려하지 않은 BoW

In [16]:
docs = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
       '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [17]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [21]:
from collections import defaultdict
word2id_1 = defaultdict(lambda : len(word2id_1))
word2id_1

defaultdict(<function __main__.<lambda>()>, {})

In [22]:
for sentense in doc_ls:
    print(sentense)
    for word in sentense:
        print(word)
        word2id_1[word]
word2id_1

['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해']
나는
양념
치킨을
좋아해
하지만
후라이드
치킨을
싫어해
['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']
나는
후라이드
치킨을
좋아해
하지만
양념
치킨을
싫어해


defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [25]:
import numpy as np
BoW_ls = []
for sentence in doc_ls:
    bow=np.zeros(len(word2id_1), dtype=int)
    print(bow)
    for word in sentence:
        bow[word2id_1[word]]+=1
    BoW_ls.append(bow.tolist())
BoW_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

# sklearn으로 BoW구현 

In [70]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
       '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [71]:
# 토큰빈도계산 : CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

#선언
count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
print(BoW.toarray())
vocab=count_vect.get_feature_names()
print(vocab)

[[1 1 1 0 1 1 1 1 2]
 [2 1 1 1 2 1 2 2 2]]
['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [72]:
from IPython.core import display as ICD
import pandas as pd

for i in range(len(docs)):
    print("문서 {} : {}".format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab))
    print('\n\n')

문서 0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2




문서 1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2

# Gensim으로 BoW구현

In [73]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', 
        '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [74]:
from gensim import corpora

doc_ls = []
for doc in docs:
    doc_ls.append(doc.split())
print(doc_ls)

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어', '오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]


In [75]:
id2word=corpora.Dictionary(doc_ls)
print(id2word)

Dictionary(9 unique tokens: ['동물원에서', '먹이를', '보고', '오늘', '원숭이를']...)


In [76]:
BoW=[]
for doc in doc_ls:
    BoW.append(id2word.doc2bow(doc))
BoW

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 2), (1, 1), (2, 1), (3, 2), (4, 1), (5, 2), (6, 2), (7, 2), (8, 1)]]

In [77]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd
vocab = [id2word[i] for i in id2word.keys()]
print(vocab)

['동물원에서', '먹이를', '보고', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리', '사과를']


In [69]:
for i in range(len(docs)):
    print("문서 {} : {}".format(i,docs[i]))
    ICD.display(pd.DataFrame([sparse2full(BoW[i],len(vocab))],columns=vocab,dtype=int))
    print("\n\n")

문서 0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를  보고  오늘  원숭이를  원숭이에게  줬어  코끼리  사과를
0      1    1   1   1     1      1   1    2    0




문서 1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를  보고  오늘  원숭이를  원숭이에게  줬어  코끼리  사과를
0      2    1   1   2     1      2   2    2    1