### TDM 직접 구현

In [38]:
docs = ['동물원 코끼리',
       '동물원 원숭이 바나나',
       '엄마 코끼리 아기 코끼리',
        '원숭이 바나나 코끼리 바나나']

In [39]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [40]:
from collections import defaultdict

wordid= defaultdict(lambda : len(wordid))
wordid

defaultdict(<function __main__.<lambda>()>, {})

In [41]:
for doc in doc_ls:
    for token in doc:
        wordid[token]
wordid

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

In [42]:
import numpy as np

In [43]:
TDM = np.zeros((len(wordid), len(doc_ls)), dtype=int)
print(TDM)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [44]:
for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[wordid[token], i] += 1 # 해당 토큰의 위치 (columns)
# 행렬로 표기 (BOW와 차이점: BOW는 1차원적 배열)
TDM

array([[1, 1, 0, 0],
       [1, 0, 2, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [45]:
import pandas as pd

doc_names = ['문서'+str(i) for i in range(len(doc_ls))]
print('doc_names', doc_names)
sorted_vocab = sorted((value,key) for key, value in wordid.items())

doc_names ['문서0', '문서1', '문서2', '문서3']


In [46]:
vocab = [v[1] for v in sorted_vocab]
df_TDM = pd.DataFrame(TDM, columns=doc_names)
df_TDM['단어'] = vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
원숭이    0    1    0    1
바나나    0    1    0    2
엄마     0    0    1    0
아기     0    0    1    0