In [1]:
### BoW 직접 구현

In [2]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
         '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [3]:
#띄어쓰기 토큰화
doc_ls= []
for doc in docs:
    doc_ls.append(doc.split(' '))
print(doc_ls)

from collections import defaultdict
word2id = defaultdict(lambda: len(word2id))
#중복단어는 하나만 씀(유니크)
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]


defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [4]:
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [5]:
import numpy as np
BoW_ls=[]
for i,doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype= int)
    print(bow)
    
    for token in doc:
        bow[word2id[token]] += 1 # 해당토큰의 위치(column)
    BoW_ls.append(bow.tolist())
# 1차원 배열
BoW_ls

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [6]:
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [7]:
from IPython.core import display as ICD

In [8]:
import pandas as pd
sorted_vocab = sorted((value,key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [10]:
vocab = []
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [11]:
for i in range (len(docs)):
    print('문서{}: {}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]],columns= vocab))
    print("\n\n")

문서0: 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1: 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

In [12]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [ ]:
### 단어의 순서를 고려하지 않은 BOW

In [33]:
docs =['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
       '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [47]:
doc_ls= []
for doc in docs:
    doc_ls.append(doc.split())
print(doc_ls)

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'], ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]


In [48]:
from collections import defaultdict

word2id = defaultdict(lambda: len(word2id))

#중복단어는 하나만 씀(유니크)
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [49]:
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [52]:
import numpy as np
BoW_ls = []
for i,doc in enumerate(doc_ls):
    bow= np.zeros(len(word2id), dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] +=1 #해당토큰의 위치(columns)
    BoW_ls.append(bow.tolist())
BoW_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [53]:
word2id

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [54]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value,key) for key, value in word2id.items())
print('sorted_vocab',sorted_vocab)

sorted_vocab [(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]


In [55]:
vocab = []
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)

vocab ['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']


In [56]:
for i in range(len(docs)): #문서 2개라 2번돌음
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
    print('\n\n')

문서0:나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1:나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1

In [57]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [58]:
###sklearn

In [59]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
         '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [64]:
# 토큰빈도계산: CounterVectorizer
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
# 선언
count_vect = CountVectorizer()
BoW = count_vect.fit_transform(docs)
print(BoW.toarray())
vocab = count_vect.get_feature_names()
print(vocab)

[[1 1 1 0 1 1 1 1 2]
 [1 0 0 1 1 0 1 1 0]]
['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [65]:
from IPython.core import display as ICD

In [77]:
import pandas as pd
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab))
    df= pd.DataFrame([BoW.toarray()[i]], columns=vocab)
    print(df)
    print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2

   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2



문서1:오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    0   0    1   1     0      1   1    0

   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    0   0    1   1     0      1   1    0





In [ ]:
###gensim

In [67]:
!pip install gensim

  Created wheel for smart-open: filename=smart_open-2.1.1-py3-none-any.whl size=112418 sha256=c69603477d0e869577f775a7b07b8ae50b8e365687e919269e4511f65d701492
  Stored in directory: c:\users\김재환\appdata\local\pip\cache\wheels\07\d8\70\da31eb9ec5ff49ac74f1a5944704029f0b6fd74fdf318ec300
Successfully built smart-open


In [78]:
from gensim import corpora

In [79]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
         '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [80]:
doc_ls= []
for doc in docs:
    doc_ls.append(doc.split())
print(doc_ls)
id2word = corpora.Dictionary(doc_ls)
print('----')
print(id2word)
BoW = []
for doc in doc_ls:
    BoW.append(id2word.doc2bow(doc))
BoW

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]
----
Dictionary(9 unique tokens: ['동물원에서', '먹이를', '보고', '오늘', '원숭이를']...)


[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 1), (3, 1), (5, 1), (6, 1), (8, 1)]]

In [81]:
BoW[0]

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)]

In [90]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd
vocab = [id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
     print('문서{}:{}'.format(i,docs[i]))
     ICD.display(pd.DataFrame([sparse2full(BoW[i],len(vocab))], columns=vocab))
     print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  2.0  0.0




문서1:오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    1.0  0.0  0.0  1.0   0.0    1.0  1.0  0.0  1.0

In [94]:
### 분리
### TDM 직접구현

In [95]:
docs=['동물원 코끼리',
      '동물원 원숭이 바나나',
      '엄마 코끼리 아기 코끼리',
      '원숭이 바나나 코끼리 바나나']

In [108]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [112]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id)) #기본 딕셔너리 만들기

for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

In [114]:
import numpy as np

TDM= np.zeros((len(word2id),len(doc_ls)), dtype= int)
print(TDM)
for i, doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token],i] +=1
TDM

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([[1, 1, 0, 0],
       [1, 0, 2, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [116]:
import pandas as pd

doc_names=['문서'+ str(i) for i in range(len(doc_ls))]
print('doc_names', doc_names)
sorted_vocab = sorted((value,key) for key, value in word2id.items())
vocab= [v[1] for v in sorted_vocab]
df_TDM=pd.DataFrame(TDM, columns=doc_names)
df_TDM['단어'] =vocab
df_TDM.set_index('단어')

doc_names ['문서0', '문서1', '문서2', '문서3']


문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
원숭이    0    1    0    1
바나나    0    1    0    2
엄마     0    0    1    0
아기     0    0    1    0

In [117]:
###sklearn패키지 활용

In [118]:
docs=['동물원 코끼리',
      '동물원 원숭이 바나나',
      '엄마 코끼리 아기 코끼리',
      '원숭이 바나나 코끼리 바나나']

In [121]:
from sklearn.feature_extraction.text import CountVectorizer
# 참고 sklearn은 DTM으로 만들어지게 설정되어있음
count_vect = CountVectorizer()
DTM = count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 2],
       [0, 2, 0, 0, 1, 1]], dtype=int64)

In [122]:
DTM.toarray().T

array([[1, 1, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 2, 1]], dtype=int64)

In [124]:
import pandas as pd

doc_names=['문서'+ str(i) for i in range(len(doc_ls))]
vocab = count_vect.get_feature_names()
print(vocab)
df_TDM=pd.DataFrame(DTM.toarray().T, columns=doc_names)
df_TDM['단어'] =vocab
df_TDM.set_index('단어')

['동물원', '바나나', '아기', '엄마', '원숭이', '코끼리']


문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
바나나    0    1    0    2
아기     0    0    1    0
엄마     0    0    1    0
원숭이    0    1    0    1
코끼리    1    0    2    1

In [125]:
###gensim

In [126]:
docs=['동물원 코끼리',
      '동물원 원숭이 바나나',
      '엄마 코끼리 아기 코끼리',
      '원숭이 바나나 코끼리 바나나']

In [128]:
import gensim
from gensim import corpora

doc_ls = [doc.split() for doc in docs]

id2word = corpora.Dictionary(doc_ls)
TDM= [id2word.doc2bow(doc) for doc in doc_ls]
TDM

[[(0, 1), (1, 1)],
 [(0, 1), (2, 1), (3, 1)],
 [(1, 2), (4, 1), (5, 1)],
 [(1, 1), (2, 2), (3, 1)]]

In [130]:
from gensim.matutils import sparse2full
import pandas as pd 
import numpy as np
doc_names=['문서'+ str(i) for i in range(len(doc_ls))]
vocab = [id2word[i] for i in id2word.keys()]
DTM_matrix = [sparse2full(doc,len(vocab)).tolist() for doc in TDM]

df_TDM = pd.DataFrame(np.array(DTM_matrix, dtype= int).T,
                     columns= doc_names)
df_TDM['단어'] =vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
바나나    0    1    0    2
원숭이    0    1    0    1
아기     0    0    1    0
엄마     0    0    1    0