## BOW 직접 구현

In [1]:
docs =['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어','오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [2]:
doc_ls =[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [11]:
from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))

for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [12]:
n_unique_words = len(word2id)
n_unique_words

9

In [13]:
import numpy as np

In [15]:
# 단어 고유 인덱스
BoW_ls =[]
for i,doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] += 1 #해당 토큰의 위치(column)
    BoW_ls.append(bow.tolist())

BoW_ls

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

- 시각화

In [32]:
!pip install ipython

In [41]:
import IPython
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value,key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [42]:
vocab = []
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [43]:
for i in range(len(docs)):
    print("문서{}: {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
    print("\n\n")

문서0: 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1: 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

In [36]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

## 단어의 순서를 고려하지 않은 BOW

In [18]:
docs1 = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
        '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [19]:
doc_ls1 =[]
for doc in docs1:
    doc_ls1.append(doc.split(' '))
doc_ls1

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [20]:
from collections import defaultdict

word2id1 = defaultdict(lambda : len(word2id1))

for doc in doc_ls1:
    for token in doc:
        word2id1[token]
word2id1

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [21]:
# 단어 고유 인덱스
BoW_ls1 =[]
for i,doc in enumerate(doc_ls1):
    bow1 = np.zeros(len(word2id1), dtype=int)
    print(bow1)
    for token in doc:
        bow1[word2id1[token]] += 1 #해당 토큰의 위치(column)
    BoW_ls1.append(bow1.tolist())

BoW_ls1

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]