## 원핫 인코딩 직접구현

In [1]:
# 인코딩 대상 단어를 담은 리스트
word_ls= ['원숭이','바나나','사과','코끼리']

In [2]:
from collections import defaultdict


#{단어:인덱스} 사전구축
word2id_dic = defaultdict(lambda: len(word2id_dic))

for word in word_ls:
    word2id_dic[word]


In [4]:
#고유단어갯수 : 4개

n_unique_words = len(word2id_dic)
n_unique_words

4

In [5]:
# 원핫 백터를 만들기 위해 비어있는 백터 생성
one_hot_vectors = np.zeros((len(word_ls), n_unique_words))
one_hot_vectors

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# 단어 고유 인덱스
for i,word in enumerate(word_ls):
    index= word2id_dic[word]
    one_hot_vectors[i,index] += 1
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## sklearn

In [12]:
word_ls

['원숭이', '바나나', '사과', '코끼리']

In [14]:
#sklearn 설치
# !pip install -U scikit-learn scipy matplotlib

Requirement already up-to-date: scipy in c:\users\user\anaconda3\envs\py36\lib\site-packages (1.5.2)
Requirement already up-to-date: matplotlib in c:\users\user\anaconda3\envs\py36\lib\site-packages (3.3.1)


In [15]:
# sklearn을 활용한 one-hot encoding

from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [16]:
# 예제 데이터 배열
values= array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [17]:
#문자열에 숫자를 붙임
label_enc = LabelEncoder() #선언
int_enc = label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3], dtype=int64)

In [22]:
#binary encode
onehot_enc=OneHotEncoder(sparse=False) #선언
# sparse=True 로 하면 행렬로 반환
# sparse=False로 하면 배열로 반환

int_enc= int_enc.reshape(len(int_enc), 1) #n:1 matrix 로 변환
onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])