# 원핫인코딩 직접구현

In [1]:
#인코딩 대상 단어를 담은 리스트
word_ls=['원숭이','바나나','사과','코끼리']

In [2]:
from collections import defaultdict
import numpy as np
#{단어:인덱스} 사전구축
word2id_dic=defaultdict(lambda:len(word2id_dic))
word2id_dic

defaultdict(<function __main__.<lambda>()>, {})

In [3]:
for word in word_ls:
    word2id_dic[word]
word2id_dic

defaultdict(<function __main__.<lambda>()>,
            {'원숭이': 0, '바나나': 1, '사과': 2, '코끼리': 3})

In [4]:
#고유단어갯수:4개
n_unique_words=len(word2id_dic)
#원핫 벡터 만들기 위해 비어있는 벡터 생성
one_hot_vectors=np.zeros((len(word_ls),n_unique_words))
n_unique_words

4

In [5]:
#단어고유 인덱스
for i,word in enumerate(word_ls):
    index=word2id_dic[word]
    one_hot_vectors[i,index]+=1
one_hot_vectors


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# sklearn

In [6]:
!pip install scikit-learn

In [7]:
#sklearn을 활용한 one-hot encoding
import sklearn
from numpy import array
from numpy import argmax #큰값부터 sorting시키는함수
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#예제 데이터 배열
values=array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [8]:
#문자열에 숫자 붙임
label_enc=LabelEncoder()
int_enc=label_enc.fit_transform(values) #세로를 가로로 맞추는..?그런거
int_enc

array([2, 0, 1, 3], dtype=int64)

In [9]:
onehot_enc=OneHotEncoder(sparse=False) #True=행렬/ False=배열
int_enc=int_enc.reshape(len(int_enc),1) #n:1 matrix로 변환
onehot_enc=onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [10]:
int_enc

array([[2],
       [0],
       [1],
       [3]], dtype=int64)

In [11]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
     '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [12]:
doc_ls=[]
#문장 1,2로 분리
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [13]:
from collections import defaultdict
import numpy as np
word2id=defaultdict(lambda:len(word2id)) #word_dic 길이만큼의 class 만들기
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [14]:
doc_ls[0]

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어']

In [15]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]]+=1
    BoW_ls.append(bow.tolist())
BoW_ls
            

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [16]:
wordindex={}
word2=[]
for voca in doc_ls[0]:
    if voca not in wordindex.keys():
        wordindex[voca]=len(wordindex)
        word2.insert(len(wordindex)-1,1)
    else:
        index=wordindex.get(voca)
        word2[index]=word2[index]+1
print(wordindex)
word2

{'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4, '원숭이에게': 5, '먹이를': 6, '줬어': 7}


[1, 1, 2, 1, 1, 1, 1, 1]

In [17]:
!pip install pandas

In [18]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab=sorted((value,key)for key, value in word2id.items())
sorted_vocab

[(0, '오늘'),
 (1, '동물원에서'),
 (2, '코끼리'),
 (3, '원숭이를'),
 (4, '보고'),
 (5, '원숭이에게'),
 (6, '먹이를'),
 (7, '줬어'),
 (8, '사과를')]

In [19]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print(vocab)

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [20]:
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [21]:
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]],columns=vocab))
    print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1:오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

# 단어의 순서를 고려하지 않은 BOW

In [22]:
docs=['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
     '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [23]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split())
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [24]:
from collections import defaultdict
word2id=defaultdict(lambda: len(word2id))

for doc in doc_ls:
    print(doc)
    for token in doc:
        word2id[token]
word2id

['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해']
['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']


defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [25]:
import numpy as np
Bow_ls=[]
for i,doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]]+=1 #해당 토큰의 위치
    BoW_ls.append(bow.tolist())
BoW_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0],
 [1, 1, 0, 0, 0, 1, 0, 1, 1],
 [1, 1, 2, 1, 1, 1, 1],
 [1, 1, 2, 1, 1, 1, 1]]

# sklearn

In [26]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
     '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

#토큰빈도계산:CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
#선언
count_vect=CountVectorizer()
BoW=count_vect.fit_transform(docs)
print(BoW.toarray())
vocab=count_vect.get_feature_names()
print(vocab)


[[1 1 1 0 1 1 1 1 2]
 [2 1 1 1 2 1 2 2 2]]
['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [27]:
import pandas as pd
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    print('\n')
    df=pd.DataFrame([BoW.toarray()[i]],columns=vocab)
    print(df)
    print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2



문서1:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2





# gensim

In [28]:
!pip install gensim

In [29]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
     '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [30]:
from gensim import corpora
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split())
print(doc_ls)
id2word=corpora.Dictionary(doc_ls)
print('----')
print(id2word)
BoW=[]
for doc in doc_ls:
    BoW.append(id2word.doc2bow(doc))
BoW

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어', '오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]
----
Dictionary(9 unique tokens: ['동물원에서', '먹이를', '보고', '오늘', '원숭이를']...)


[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 2), (1, 1), (2, 1), (3, 2), (4, 1), (5, 2), (6, 2), (7, 2), (8, 1)]]

In [31]:
BoW[0]

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)]

In [32]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd
vocab=[id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([sparse2full(BoW[i],len(vocab))],columns=vocab))
    print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  2.0  0.0




문서1:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    2.0  1.0  1.0  2.0   1.0    2.0  2.0  2.0  1.0

# TDM 직접구현

In [33]:
docs=['동물원 코끼리',
     '동물원 원숭이 바나나',
     '엄마 코끼리 아기 코끼리',
     '원숭이 바나나 코끼리 바나나']
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [34]:
from collections import defaultdict
word2id=defaultdict(lambda:len(word2id))
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

In [35]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]]+=1  # [ ]는 인덱스!
    BoW_ls.append(bow.tolist())
    
BoW_ls

[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]


[[1, 1, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0],
 [0, 2, 0, 0, 1, 1],
 [0, 1, 1, 2, 0, 0]]

In [36]:
a=pd.DataFrame(BoW_ls,columns=word2id.items())
a

동물원 코끼리 원숭이 바나나 엄마 아기
    0   1   2   3  4  5
0   1   1   0   0  0  0
1   1   0   1   1  0  0
2   0   2   0   0  1  1
3   0   1   1   2  0  0

In [37]:
TDM=np.zeros((len(word2id),len(doc_ls)),dtype=int)
TDM

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
for i,doc in enumerate(doc_ls):
    for token in doc:
        TDM[word2id[token],i]+=1 #이미 리스트 형태이므로 append할필요 없음
TDM

array([[1, 1, 0, 0],
       [1, 0, 2, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0]])

In [44]:
doc_names=['문서'+str(i) for i in range(len(doc_ls))]
sorted_vocab=sorted((value,key)for key,value in word2id.items())
vocab=[v[1] for v in sorted_vocab]
df_TDM=pd.DataFrame(TDM,columns=doc_names)
df_TDM['단어']=vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
코끼리    1    0    2    1
원숭이    0    1    0    1
바나나    0    1    0    2
엄마     0    0    1    0
아기     0    0    1    0

# sklearn

In [45]:
docs

['동물원 코끼리', '동물원 원숭이 바나나', '엄마 코끼리 아기 코끼리', '원숭이 바나나 코끼리 바나나']

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer()
DTM=count_vect.fit_transform(docs)
DTM.toarray()

array([[1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 1, 0],
       [0, 0, 1, 1, 0, 2],
       [0, 2, 0, 0, 1, 1]], dtype=int64)

In [47]:
DTM.toarray().T

array([[1, 1, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 2, 1]], dtype=int64)

In [54]:
doc_names=['문서'+str(i) for i in range(len(doc_ls))]
vocab=count_vect.get_feature_names()
vocab
df_TDM=pd.DataFrame(DTM.toarray().T,columns=doc_names)
df_TDM['단어']=vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
바나나    0    1    0    2
아기     0    0    1    0
엄마     0    0    1    0
원숭이    0    1    0    1
코끼리    1    0    2    1

# gensim

In [48]:
import gensim
from gensim import corpora

doc_ls=[doc.split() for doc in docs]
id2word=corpora.Dictionary(doc_ls)
TDM=[id2word.doc2bow(doc) for doc in doc_ls]
TDM

[[(0, 1), (1, 1)],
 [(0, 1), (2, 1), (3, 1)],
 [(1, 2), (4, 1), (5, 1)],
 [(1, 1), (2, 2), (3, 1)]]

In [55]:
from gensim.matutils import sparse2full
DTM_matrix=[sparse2full(doc,len(vocab)).tolist() for doc in TDM]
df_TDM=pd.DataFrame(np.array(DTM_matrix,dtype=int).T,columns=doc_names)
df_TDM['단어']=vocab
df_TDM.set_index('단어')

문서0  문서1  문서2  문서3
단어                     
동물원    1    1    0    0
바나나    1    0    2    1
아기     0    1    0    2
엄마     0    1    0    1
원숭이    0    0    1    0
코끼리    0    0    1    0

In [56]:
DTM_matrix

[[1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 2.0, 0.0, 0.0, 1.0, 1.0],
 [0.0, 1.0, 2.0, 1.0, 0.0, 0.0]]

# TF-IDF 

In [235]:
docs=['오늘 동물원에서 원숭이와 코끼리를 봤어','동물원에서 원숭이에게 바나나를 줬어 바나나를']
doc_ls=[i.split(' ') for i in docs]
doc_ls

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [283]:
from collections import defaultdict
word2id=defaultdict(lambda:len(word2id))

for doc in doc_ls:
    for i in doc:
        word2id[i]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이와': 2,
             '코끼리를': 3,
             '봤어': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

In [198]:
TDM=[]
for i,doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for i in doc:
        bow[word2id[i]]+=1
    TDM.append(bow.tolist())

TDM

[0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0]


[[1, 1, 1, 1, 1, 0, 0, 0], [0, 1, 0, 0, 0, 1, 2, 1]]

In [199]:
doc_names=[i for i in word2id]
doc1=pd.DataFrame(index=doc_names)
doc2=pd.DataFrame(index=doc_names)
doc1

Empty DataFrame
Columns: []
Index: [오늘, 동물원에서, 원숭이와, 코끼리를, 봤어, 원숭이에게, 바나나를, 줬어]

In [200]:
doc1['문서내 토큰 빈도']=TDM[0]
doc2['문서내 토큰 빈도']=TDM[1]

In [204]:
doc1['문서내 전체 토큰빈도']=len(doc_ls[0])
doc2['문서내 전체 토큰빈도']=len(doc_ls[1])

In [205]:
for i in doc1:
    doc1['TF']=doc1['문서내 토큰 빈도']/doc1['문서내 전체 토큰빈도']

In [206]:
for i in doc2:
    doc2['TF']=doc2['문서내 토큰 빈도']/doc2['문서내 전체 토큰빈도']

In [207]:
doc1

문서내 토큰 빈도  문서내 전체 토큰빈도   TF
오늘             1            5  0.2
동물원에서          1            5  0.2
원숭이와           1            5  0.2
코끼리를           1            5  0.2
봤어             1            5  0.2
원숭이에게          0            5  0.0
바나나를           0            5  0.0
줬어             0            5  0.0

In [208]:
doc2

문서내 토큰 빈도  문서내 전체 토큰빈도   TF
오늘             0            5  0.0
동물원에서          1            5  0.2
원숭이와           0            5  0.0
코끼리를           0            5  0.0
봤어             0            5  0.0
원숭이에게          1            5  0.2
바나나를           2            5  0.4
줬어             1            5  0.2

In [213]:
import numpy as np

DTM=np.zeros((len(doc_ls),len(word2id)),dtype=int)
for i,doc in enumerate(doc_ls):
    for token in doc:
        DTM[i,word2id[token]]+=1

DTM

array([[1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

In [221]:
def computeTF(DTM):
    doc_len=len(DTM)#문서갯수 2개
    word_len=len(DTM[0]) #토큰갯수 8개
    tf=np.zeros((doc_len,word_len))
    
    for doc_i in range(doc_len):
        for word_i in range(word_len):
            tf[doc_i,word_i]=DTM[doc_i,word_i]/DTM[doc_i].sum()
    return tf

In [222]:
computeTF(DTM)

array([[0.2, 0.2, 0.2, 0.2, 0.2, 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. , 0.2, 0.4, 0.2]])

## idf

In [143]:
BoW_ls=[]
for i,doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for i in doc:
        bow[word2id[i]]+=1
    BoW_ls.append(bow.tolist())

BoW_ls

BoW_ls[1]

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 1, 1, 1, 0, 0, 0, 0], [0, 1, 0, 0, 0, 1, 2, 1, 0]]

In [154]:
idf=pd.DataFrame(index=doc_names)
idf['문서수']=len(doc_ls)
idf['토큰이 등장한 문서수']

문서수
오늘       2
동물원에서    2
원숭이와     2
코끼리를     2
봤어       2
원숭이에게    2
바나나를     2
줬어       2

In [236]:
doc_ls

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [284]:
from IPython.core import display as ICD
sorted_vocab=sorted((value,key) for key, value in word2id.items())
print(sorted_vocab)

[(0, '오늘'), (1, '동물원에서'), (2, '원숭이와'), (3, '코끼리를'), (4, '봤어'), (5, '원숭이에게'), (6, '바나나를'), (7, '줬어')]


In [285]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])

vocab

['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어', '원숭이에게', '바나나를', '줬어']

In [293]:
for i in doc_ls:
    bow=np.zeros(len(word2id),dtype=int)
    for token in i:
        if token == vocab:
            bow[word2id[token]]=1
            
        else:
            bow[word2id[token]]=0

bow

array([0, 0, 0, 0, 0, 0, 0, 0])

In [295]:
bow=np.zeros(len(word2id),dtype=int)
for i in range(0,len(vocab)):
    if (vocab[i] in doc_ls[0])==True:
        bow[i]=bow[i]+1
    if(vocab[i] in doc_ls[1])==True:
        bow[i]=bow[i]+1

bow

array([1, 2, 1, 1, 1, 1, 1, 1])

In [247]:
DTM

array([[1, 1, 1, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 2, 1]])

In [252]:
import math
def computeIDF(DTM):
    doc_len=len(DTM)
    word_len=len(DTM[0])
    
    idf=np.zeros(word_len)
    
    for i in range(word_len):
        idf[i]=math.log10(doc_len/np.count_nonzero(DTM[:,i]))
    return idf
    
    

In [253]:
computeIDF(DTM)

array([0.30103, 0.     , 0.30103, 0.30103, 0.30103, 0.30103, 0.30103,
       0.30103])

# Sklearn

In [2]:
docs=['오늘 동물원에서 원숭이와 코끼리를 봤어','동물원에서 원숭이에게 바나나를 줬어 바나나를']
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf=tfidf.fit(docs)
tfidf.transform(docs).toarray()
vocab=tfidf.get_feature_names()

In [3]:
vocab

['동물원에서', '바나나를', '봤어', '오늘', '원숭이에게', '원숭이와', '줬어', '코끼리를']

In [5]:
tfidf.transform(docs).toarray()

array([[0.33517574, 0.        , 0.47107781, 0.47107781, 0.        ,
        0.47107781, 0.        , 0.47107781],
       [0.27894255, 0.78408803, 0.        , 0.        , 0.39204401,
        0.        , 0.39204401, 0.        ]])

In [7]:
import pandas as pd
df=pd.DataFrame(tfidf.transform(docs).toarray(),columns=vocab)
df

동물원에서      바나나를        봤어        오늘     원숭이에게      원숭이와        줬어  \
0  0.335176  0.000000  0.471078  0.471078  0.000000  0.471078  0.000000   
1  0.278943  0.784088  0.000000  0.000000  0.392044  0.000000  0.392044   

       코끼리를  
0  0.471078  
1  0.000000

# Gensim

In [18]:
import gensim
from gensim import corpora
from gensim.models import TfidfModel
docs=['오늘 동물원에서 원숭이와 코끼리를 봤어','동물원에서 원숭이에게 바나나를 줬어 바나나를']
doc_ls=[doc.split() for doc in docs]
print(doc_ls)
id2word=corpora.Dictionary(doc_ls)
print(id2word)

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'], ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]
Dictionary(8 unique tokens: ['동물원에서', '봤어', '오늘', '원숭이와', '코끼리를']...)


In [11]:
TDM=[id2word.doc2bow(doc) for doc in doc_ls]
TDM

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)], [(0, 1), (5, 2), (6, 1), (7, 1)]]

In [15]:
model=TfidfModel(TDM)
print(model)

TfidfModel(num_docs=2, num_nnz=9)


In [16]:
tfidf=model[TDM]
tfidf[0]

[(1, 0.5), (2, 0.5), (3, 0.5), (4, 0.5)]

In [21]:
import pandas as pd
from gensim.matutils import sparse2full
vocab=[id2word[i] for i in id2word.keys()]
TDM_matrix=[sparse2full(doc,len(vocab)).tolist() for doc in tfidf]
pd.DataFrame(TDM_matrix,columns=vocab)

동물원에서   봤어   오늘  원숭이와  코끼리를      바나나를     원숭이에게        줬어
0    0.0  0.5  0.5   0.5   0.5  0.000000  0.000000  0.000000
1    0.0  0.0  0.0   0.0   0.0  0.816497  0.408248  0.408248