# 원핫인코딩 직접구현

In [1]:
#인코딩 대상 단어를 담은 리스트
word_ls=['원숭이','바나나','사과','코끼리']

In [3]:
from collections import defaultdict
import numpy as np
#{단어:인덱스} 사전구축
word2id_dic=defaultdict(lambda:len(word2id_dic))
word2id_dic

defaultdict(<function __main__.<lambda>()>, {})

In [9]:
for word in word_ls:
    word2id_dic[word]
word2id_dic

defaultdict(<function __main__.<lambda>()>,
            {'원숭이': 0, '바나나': 1, '사과': 2, '코끼리': 3})

In [7]:
#고유단어갯수:4개
n_unique_words=len(word2id_dic)
#원핫 벡터 만들기 위해 비어있는 벡터 생성
one_hot_vectors=np.zeros((len(word_ls),n_unique_words))
n_unique_words

4

In [8]:
#단어고유 인덱스
for i,word in enumerate(word_ls):
    index=word2id_dic[word]
    one_hot_vectors[i,index]+=1
one_hot_vectors


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# sklearn

In [14]:
!pip install scikit-learn

In [15]:
#sklearn을 활용한 one-hot encoding
import sklearn
from numpy import array
from numpy import argmax #큰값부터 sorting시키는함수
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#예제 데이터 배열
values=array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [25]:
#문자열에 숫자 붙임
label_enc=LabelEncoder()
int_enc=label_enc.fit_transform(values) #세로를 가로로 맞추는..?그런거
int_enc

array([2, 0, 1, 3], dtype=int64)

In [29]:
onehot_enc=OneHotEncoder(sparse=False) #True=행렬/ False=배열
int_enc=int_enc.reshape(len(int_enc),1) #n:1 matrix로 변환
onehot_enc=onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [30]:
int_enc

array([[2],
       [0],
       [1],
       [3]], dtype=int64)

In [33]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
     '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [34]:
doc_ls=[]
#문장 1,2로 분리
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [111]:
from collections import defaultdict
import numpy as np
word2id=defaultdict(lambda:len(word2id)) #word_dic 길이만큼의 class 만들기
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

In [78]:
len(word_dic)
num_word_dic=np.zeros((1,len(word_dic)))
num_word_dic

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
doc_ls[0]

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어']

In [113]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]]+=1
    BoW_ls.append(bow.tolist())
BoW_ls
            

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [49]:
wordindex={}
word2=[]
for voca in doc_ls[0]:
    if voca not in wordindex.keys():
        wordindex[voca]=len(wordindex)
        word2.insert(len(wordindex)-1,1)
    else:
        index=wordindex.get(voca)
        word2[index]=word2[index]+1
print(wordindex)
word2

{'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4, '원숭이에게': 5, '먹이를': 6, '줬어': 7}


[1, 1, 2, 1, 1, 1, 1, 1]

In [115]:
!pip install pandas

In [116]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab=sorted((value,key)for key, value in word2id.items())
sorted_vocab

[(0, '오늘'),
 (1, '동물원에서'),
 (2, '코끼리'),
 (3, '원숭이를'),
 (4, '보고'),
 (5, '원숭이에게'),
 (6, '먹이를'),
 (7, '줬어'),
 (8, '사과를')]

In [117]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print(vocab)

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [118]:
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [126]:
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]],columns=vocab))
    print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1:오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

# 단어의 순서를 고려하지 않은 BOW

In [128]:
docs=['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
     '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [129]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split())
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [132]:
from collections import defaultdict
word2id=defaultdict(lambda: len(word2id))

for doc in doc_ls:
    print(doc)
    for token in doc:
        word2id[token]
word2id

['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해']
['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']


defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [148]:
import numpy as np
Bow_ls=[]
for i,doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]]+=1 #해당 토큰의 위치
        BoW_ls.append(bow.tolist())
BoW_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0],
 [1, 1, 1, 1, 0, 0, 0],
 [1, 1, 1, 1, 1, 0, 0],
 [1, 1, 1, 1, 1, 1, 0],
 [1, 1, 2, 1, 1, 1, 0],
 [1, 1, 2, 1, 1, 1, 1],
 [1, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 1, 0],
 [1, 0, 1, 0, 0, 1, 0],
 [1, 0, 1, 1, 0, 1, 0],
 [1, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 1, 0],
 [1, 1, 2, 1, 1, 1, 0],
 [1, 1, 2, 1, 1, 1, 1]]

In [149]:
from IPython.core import display as ICD
sorted_vocab=sorted((value,key) for key,value in word2id.items())
vocab=[v[1] for v in sorted_vocab]

for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]],columns=vocab))
    print('\n\n')

문서0:나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   0    0    0    0     0    0




문서1:나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    0    0    0     0    0

# sklearn

In [150]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
     '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

#토큰빈도계산:CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
#선언
count_vect=CountVectorizer()
BoW=count_vect.fit_transform(docs)
print(BoW.toarray())
vocab=count_vect.get_feature_names()
print(vocab)


[[1 1 1 0 1 1 1 1 2]
 [2 1 1 1 2 1 2 2 2]]
['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [155]:
import pandas as pd
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    print('\n')
    df=pd.DataFrame([BoW.toarray()[i]],columns=vocab)
    print(df)
    print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2



문서1:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2





# gensim

In [192]:
!pip install gensim

  Created wheel for smart-open: filename=smart_open-2.1.1-py3-none-any.whl size=112418 sha256=76c623a8fa08b59e562d3946b842ab09e58bed2f81cd87263bdb5e8355d5e019
  Stored in directory: c:\users\home\appdata\local\pip\cache\wheels\d5\75\1d\d3da0d094f5e2ea61bddb9cb8cd4bd3ab9fb648e7269620855
Successfully built smart-open


In [194]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
     '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [195]:
from gensim import corpora
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split())
print(doc_ls)
id2word=corpora.Dictionary(doc_ls)
print('----')
print(id2word)
BoW=[]
for doc in doc_ls:
    BoW.append(id2word.doc2bow(doc))
BoW

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어', '오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]
----
Dictionary(9 unique tokens: ['동물원에서', '먹이를', '보고', '오늘', '원숭이를']...)


[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 2), (1, 1), (2, 1), (3, 2), (4, 1), (5, 2), (6, 2), (7, 2), (8, 1)]]

In [196]:
BoW[0]

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)]

In [200]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd
vocab=[id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
    print('문서{}:{}'.format(i,docs[i]))
    ICD.display(pd.DataFrame([sparse2full(BoW[i],len(vocab))],columns=vocab))
    print('\n\n')

문서0:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  2.0  0.0




문서1:오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    2.0  1.0  1.0  2.0   1.0    2.0  2.0  2.0  1.0

# TDM 직접구현

In [158]:
docs=['동물원 코끼리',
     '동물원 원숭이 바나나',
     '엄마 코끼리 아기 코끼리',
     '원숭이 바나나 코끼리 바나나']
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['동물원', '코끼리'],
 ['동물원', '원숭이', '바나나'],
 ['엄마', '코끼리', '아기', '코끼리'],
 ['원숭이', '바나나', '코끼리', '바나나']]

In [159]:
from collections import defaultdict
word2id=defaultdict(lambda:len(word2id))
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'동물원': 0, '코끼리': 1, '원숭이': 2, '바나나': 3, '엄마': 4, '아기': 5})

In [176]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]]+=1
    BoW_ls.append(bow.tolist())
    
BoW_ls

[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]
[0 0 0 0 0 0]


[[1, 1, 0, 0, 0, 0],
 [1, 0, 1, 1, 0, 0],
 [0, 2, 0, 0, 1, 1],
 [0, 1, 1, 2, 0, 0]]

In [184]:
a=pd.DataFrame(BoW_ls,columns=word2id.items())
a

동물원 코끼리 원숭이 바나나 엄마 아기
    0   1   2   3  4  5
0   1   1   0   0  0  0
1   1   0   1   1  0  0
2   0   2   0   0  1  1
3   0   1   1   2  0  0