In [1]:
import pandas as pd
df=pd.read_csv('C:/Users/Home/naivebayes_example.csv')
df

mail  label
0          i love you      1
1  love happy weekend      1
2       bore work job      0
3          i hate you      0
4        bore weekend      0
5      happy together      1

In [2]:
df_p=[]
df_n=[]
for i,row in df.iterrows():
    print(df.loc[i].mail)

i love you
love happy weekend
bore work job
i hate you
bore weekend
happy together


In [3]:
for i, row in df.iterrows():
    if df.loc[i].label==1:
        df_p.append(df.loc[i].mail)
    else:
        df_n.append(df.loc[i].mail)

df_p

['i love you', 'love happy weekend', 'happy together']

In [4]:
df_n

['bore work job', 'i hate you', 'bore weekend']

In [5]:
docs=['i love you','love happy weekend', 'bore work job','i hate you','bore weekend'
       ,'happy together']
doc_ls=[]
for i in docs:
    doc_ls.append(i.split(' '))

doc_ls

[['i', 'love', 'you'],
 ['love', 'happy', 'weekend'],
 ['bore', 'work', 'job'],
 ['i', 'hate', 'you'],
 ['bore', 'weekend'],
 ['happy', 'together']]

In [6]:
from collections import defaultdict
word2id=defaultdict(lambda:len(word2id))
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'i': 0,
             'love': 1,
             'you': 2,
             'happy': 3,
             'weekend': 4,
             'bore': 5,
             'work': 6,
             'job': 7,
             'hate': 8,
             'together': 9})

In [7]:
from IPython.core import display as ICD
sorted_vocab=sorted((value,key) for key,value in word2id.items())
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
vocab

['i',
 'love',
 'you',
 'happy',
 'weekend',
 'bore',
 'work',
 'job',
 'hate',
 'together']

In [8]:
import numpy as np
positive=[]
for i,doc in enumerate(doc_ls):
    positive=np.zeros(len(word2id),dtype=int)
    
negative=[]
for i,doc in enumerate(doc_ls):
    negative=np.zeros(len(word2id),dtype=int)
positive

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
df_n_split=[]
for i in df_n:
    df_n_split.append(i.split(' '))

df_n_split

df_p_split=[]
for i in df_p:
    df_p_split.append(i.split(' '))

df_p_split

[['i', 'love', 'you'], ['love', 'happy', 'weekend'], ['happy', 'together']]

In [10]:
for i in range(0,len(vocab)):
    if (vocab[i] in df_n[0])==True:
        negative[i]=negative[i]+1
    if(vocab[i] in df_n[1])==True:
        negative[i]=negative[i]+1
    if(vocab[i] in df_n[2])==True:
        negative[i]=negative[i]+1

negative

array([1, 0, 1, 0, 1, 2, 1, 1, 1, 0])

In [11]:
for i in range(0,len(vocab)):
    if (vocab[i] in df_p[0])==True:
        positive[i]=positive[i]+1
    if(vocab[i] in df_p[1])==True:
        positive[i]=positive[i]+1
    if(vocab[i] in df_p[2])==True:
        positive[i]=positive[i]+1

positive

array([1, 2, 1, 2, 1, 0, 0, 0, 0, 1])

In [12]:
df1=pd.DataFrame(index=vocab)

positive.reshape(10,1)
df1['positive']=positive

negative.reshape(10,1)
df1['negative']=negative

df1

positive  negative
i                1         1
love             2         0
you              1         1
happy            2         0
weekend          1         1
bore             0         2
work             0         1
job              0         1
hate             0         1
together         1         0

## 2. 조건부확률 구하기

In [23]:
p_positive=[]
for i in df1['positive']:
     p_positive.append((i+1)/(positive.sum()+len(vocab)))

p_positive

[0.1111111111111111,
 0.16666666666666666,
 0.1111111111111111,
 0.16666666666666666,
 0.1111111111111111,
 0.05555555555555555,
 0.05555555555555555,
 0.05555555555555555,
 0.05555555555555555,
 0.1111111111111111]

In [24]:
p_negative=[]
for i in df1['negative']:
     p_negative.append((i+1)/(negative.sum()+len(vocab)))

p_negative

[0.1111111111111111,
 0.05555555555555555,
 0.1111111111111111,
 0.05555555555555555,
 0.1111111111111111,
 0.16666666666666666,
 0.1111111111111111,
 0.1111111111111111,
 0.1111111111111111,
 0.05555555555555555]

## 3. p(positive|happy,weekend) 구하기

# Using sklearn

In [14]:
import pandas as pd
input_file=pd.read_csv('C:/Users/Home/naivebayes_example.csv')
input_file

mail  label
0          i love you      1
1  love happy weekend      1
2       bore work job      0
3          i hate you      0
4        bore weekend      0
5      happy together      1

In [15]:
x_train=list(input_file['mail'])
y_train=list(input_file['label'])
print(x_train)
print(y_train)

['i love you', 'love happy weekend', 'bore work job', 'i hate you', 'bore weekend', 'happy together']
[1, 1, 0, 0, 0, 1]


In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB

count_vect=CountVectorizer()
x_train_counts=count_vect.fit_transform(x_train)
clf=MultinomialNB().fit(x_train_counts,y_train)

In [17]:
print(clf.predict(count_vect.transform(['happy weekend'])))
print(clf.predict_proba(count_vect.transform(['happy weekend'])))

[1]
[[0.25 0.75]]
