In [1]:
from collections import defaultdict
import numpy as np

In [2]:
docs=['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
     "오늘 동물원에서 원숭이에게 사과를 줬어"]
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [3]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [4]:
from collections import defaultdict     
word2id=defaultdict(lambda:len(word2id))    #여기서도 빈 딕셔너리 만들어 줘야
word2id

defaultdict(<function __main__.<lambda>()>, {})

In [5]:
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

1. 토큰 등장 회수를 어떻게 셀 것인가
2. 각 인덱스에 어떻게 집어넣을 것인가

In [10]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]]+=1 #해당토큰의 위치
    BoW_ls.append(bow.tolist())
#1차원 배열
BoW_ls

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [12]:
!pip install pandas

In [13]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab=sorted((value,key)for key, value in word2id.items())
print('sorted_vocab',sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [14]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print("vocab",vocab)

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']


In [16]:
for i in range(len(docs)):
    print("문서{} : {}".format(i,docs[i]))
    ICD.display(pd.DataFrame(BoW_ls,columns=vocab))
    print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0
1   1      1    0     0   0      1    0   1    1




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0
1   1      1    0     0   0      1    0   1    1

# 단어의 순서를 고려하지 않은 BoW

In [17]:
docs=['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
     "나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해"]
docs

['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해', '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [18]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [19]:
from collections import defaultdict     
word2id=defaultdict(lambda:len(word2id))  #여기서도 빈 딕셔너리 만들어 줘야
word2id

defaultdict(<function __main__.<lambda>()>, {})

In [28]:
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [21]:
import numpy as np
BoW_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]]+=1 #해당토큰의 위치
    BoW_ls.append(bow.tolist())
#1차원 배열
BoW_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [30]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab=sorted((value,key)for key, value in word2id.items())
print('sorted_vocab',sorted_vocab)

sorted_vocab [(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]


In [23]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print("vocab",vocab)

vocab ['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']


In [24]:
for i in range(len(docs)):
    print("문서{} : {}".format(i,docs[i]))
    ICD.display(pd.DataFrame(BoW_ls,columns=vocab))
    print("\n\n")

문서0 : 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1
1   1   1    2    1    1     1    1




문서1 : 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1
1   1   1    2    1    1     1    1