In [1]:
# 인코딩 대상 단어를 담은 리스트
word_ls = ['원숭이','바나나','사과','코끼리']

In [2]:
from collections import defaultdict
import numpy as np

In [18]:
# {단어:인덱스} 사전구축
word2id_dic = defaultdict(lambda:len(word2id_dic))
word2id_dic

# 빈 딕셔너리를 하나 만들어 준다. 

defaultdict(<function __main__.<lambda>>, {})

In [4]:
for word in word_ls:
    word2id_dic[word]

In [5]:
word2id_dic

defaultdict(<function __main__.<lambda>>,
            {'바나나': 1, '사과': 2, '원숭이': 0, '코끼리': 3})

In [6]:
# 고유단어갯수 : 4개
n_unique_words = len(word2id_dic)
n_unique_words

#생략해도 가능

4

In [7]:
# 원핫 벡터를 만들기 위해 비어있는 벡터 생성
one_hot_vectors = np.zeros((len(word_ls), n_unique_words))
one_hot_vectors

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# 단어 고유 인덱스
for i,word in enumerate(word_ls):
    index = word2id_dic[word]
    one_hot_vectors[i,index] += 1 # 단어 고유 인덱스에 1을 더해줌.
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Sklearn 싸이키런

In [9]:
#sklearn 을 활용한 one-hot encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 예제 데이터 배열
values = array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [10]:
# 문자열에 숫자를 붙임

#선언
label_enc = LabelEncoder() 

int_enc = label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3])

In [11]:
# binary encode

#선언
onehot_enc = OneHotEncoder(sparse=False) 
int_enc = int_enc.reshape(len(int_enc), 1) # n:1 matrix로 변환
int_enc

array([[2],
       [0],
       [1],
       [3]])

In [12]:
onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

 ## BOW 직접구현
 

In [13]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
       '오늘 동물원에서 원숭이에게 사과를 줬어']
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이에게 사과를 줬어']

In [14]:
# 띄어쓰기 토큰화
doc_ls = []
for doc in docs:
    doc_ls.append(doc.split(' '))

doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

In [15]:
from collections import defaultdict
word2id = defaultdict(lambda : len(word2id))

for doc in doc_ls:
    for token in doc:
        word2id[token]

word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '먹이를': 6,
             '보고': 4,
             '사과를': 8,
             '오늘': 0,
             '원숭이를': 3,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리': 2})

In [16]:
import numpy as np
BoW_ls =[]
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] += 1 #해당 토큰의 위치(column)
    BoW_ls.append(bow.tolist())
#1차원 배열
BoW_ls

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [17]:
word2id

defaultdict(<function __main__.<lambda>>,
            {'동물원에서': 1,
             '먹이를': 6,
             '보고': 4,
             '사과를': 8,
             '오늘': 0,
             '원숭이를': 3,
             '원숭이에게': 5,
             '줬어': 7,
             '코끼리': 2})

In [21]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value, key) for key, value in word2id.items())
print('sorted_vocab',sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]


In [23]:
vocab = []
for v in sorted_vocab:
  vocab.append(v[1])
print('vocab',vocab)

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']
